name: Build and Test C++17

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies (including googletest)
        run: |
          brew update
          brew install googletest

      - name: Configure and build
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_PREFIX_PATH="$(brew --prefix)" -DCMAKE_CXX_STANDARD=17
          make

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
