name: Build, Format, Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install clang-format
        run: brew install clang-format

      - name: Format with clang-format
        run: |
          find . -type f \( -name "*.cpp" -o -name "*.h" -o -name "*.cu" \) -exec clang-format -i {} +