name: Build and Test C++17

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_CXX_STANDARD=17
          cmake --build .

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
